/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helpers from "./helpers";
export type { helpers };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { StakingContract } from "./StakingContract";
