/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VampireBloodToken } from "./VampireBloodToken";
export type { VampireStakeToken } from "./VampireStakeToken";
