/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VampireBloodToken__factory } from "./VampireBloodToken__factory";
export { VampireStakeToken__factory } from "./VampireStakeToken__factory";
