/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StakingContractV2Test__factory } from "./StakingContractV2Test__factory";
export { TestToken__factory } from "./TestToken__factory";
