/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestToken } from "./TestToken";
export type { VampireStakeV2Helper } from "./VampireStakeV2Helper";
