/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakingContractV2Test } from "./StakingContractV2Test";
export type { TestToken } from "./TestToken";
